### ISSUE TITLE
[Feature] [배달 - Step1] 배달정보 조회 API

### ISSUE THREAD

**Issue by chyn00** [f-lab-edu/your-delivery#60]
## 목표
배달은 Store에서 요청하는 것이기 때문에, 주문이 정상적으로 이루어져서,
배달이 성공적으로 시작되었는지 Return 해주는 Event를 만들어준다.

## 방법(TBD 미정)
어플리케이션에서 API로 Call하는 방법이 있고, Alaram, Pub/sub 이벤트 등을 확인하여, 실시간으로 배달 성공여부를 전달 받는 것을 구현해봐도 좋을 것 같다.

## 대안
Search 후 대안 작성

**Comment by f-lab-lion** [comment]
배달쪽은 일단 보류하도록 해요.
주문 성공까지를 1차 목표로 하면 좋을것같습니다.
고객이 가게를 이용하는것까지가 우선입니다.

1. 주문 : 고객 -> 가게
2. 배달 : 가게  -> 라이더

배달까지 하게되면 가게를 actor로 하여 라이더를 external로 구현해야하기때문에 지금으로서는 개발범위에 넣기 힘들어 보여요

**Comment by chyn00** [comment]
네 멘토님 말씀주신 것처럼 기한 내 개발범위까지 구현이 어려울 것 같습니다.
피드백 주셔서 감사합니다.
